### ISSUE TITLE
error: [WinError 2], Windows10, Python 3.6.2, installing issues. 

### ISSUE THREAD

**Issue by hertzane** [lucasb-eyer/pydensecrf#70] opened 2018-07-10 13:34 UTC
Hello,

I can not install pydensecrf in windows10, Python 3.6.2, and i do not konw how to fix it?
Problems show as a follow: 
best regard!

Huang

```

(C:\ProgramData\Anaconda3) C:\WINDOWS\system32>pip install pydensecrf
Collecting pydensecrf
  Using cached https://files.pythonhosted.org/packages/31/5a/1c2ab48e8019d282c128bc5c621332267bb954d32eecdda3ba57306b1551/pydensecrf-1.0rc3.tar.gz
Building wheels for collected packages: pydensecrf
  Running setup.py bdist_wheel for pydensecrf ... error
  Complete output from command c:\programdata\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\zhaoj\\AppData\\Local\\Temp\\pip-install-zh5d1gcm\\pydensecrf\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\zhaoj\AppData\Local\Temp\pip-wheel-e4pw08o_ --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\pydensecrf
  copying pydensecrf\utils.py -> build\lib.win-amd64-3.6\pydensecrf
  copying pydensecrf\__init__.py -> build\lib.win-amd64-3.6\pydensecrf
  running build_ext
  error: [WinError 2] 系统找不到指定的文件。

  ----------------------------------------
  Failed building wheel for pydensecrf
  Running setup.py clean for pydensecrf
Failed to build pydensecrf
Installing collected packages: pydensecrf
  Running setup.py install for pydensecrf ... error
    Complete output from command c:\programdata\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\zhaoj\\AppData\\Local\\Temp\\pip-install-zh5d1gcm\\pydensecrf\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\zhaoj\AppData\Local\Temp\pip-record-o5egd6b8\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\pydensecrf
    copying pydensecrf\utils.py -> build\lib.win-amd64-3.6\pydensecrf
    copying pydensecrf\__init__.py -> build\lib.win-amd64-3.6\pydensecrf
    running build_ext
    error: [WinError 2] 系统找不到指定的文件。

    ----------------------------------------
Command "c:\programdata\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\zhaoj\\AppData\\Local\\Temp\\pip-install-zh5d1gcm\\pydensecrf\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\zhaoj\AppData\Local\Temp\pip-record-o5egd6b8\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\zhaoj\AppData\Local\Temp\pip-install-zh5d1gcm\pydensecrf\

(C:\ProgramData\Anaconda3) C:\WINDOWS\system32>

```

**Comment by lucasb-eyer** [comment] 2018-07-15 10:54
Hi, I believe this is a duplicate of #47, so I'm closing this one in order to keep a single issue for this problem.

Unfortunately, I currently do not have access to a windows development machine, so I cannot help. The error message is "系统找不到指定的文件" and means "The system can not find the file specified", correct? What file is it about? I don't understand the error here.

**Closed by lucasb-eyer** 2018-07-15 10:54 UTC
Labels: Windows, help wanted

**Comment by lucasb-eyer** [comment] 2018-07-15 10:56
Maybe just a guess: did you install a recent version of Cython? Did you check [both options linked here in the README](https://github.com/lucasb-eyer/pydensecrf#problems-on-windowsvs)?

**Comment by dominhtrieuvhp** [comment] 2021-05-27 21:11
Step1: download package of pydensecrf compatible with python version from link https://anaconda.org/conda-forge/pydensecrf/files?version=1.0rc2&page=2 Step2: Extract the package and copy two subfolders "pydensecrf and pydensecrf-1.0rc2.dist-info" in folder "Lib" to installed folder of python (Example: C:\Python 3.6\Lib\site-packages)
