### ISSUE TITLE
Can't import the library

### ISSUE THREAD

**Issue by JiayunLi** [lucasb-eyer/pydensecrf#28] opened 2017-02-23 04:12 UTC
Hi, 

I am trying to install this library with pip install. The library seemed to be successfully installed. My cython is v 0.24.1. But when I tried to import pydensecrf.densecrf, I got .../pydensecrf/densecrf.so: undefined symbol: _ZTINSt8ios_base7failureB5cxx11E error. 

I would really appreciate if anyone could help me with this?

**Comment by lucasb-eyer** [comment] 2017-02-23 09:07
At first, this seems to be a problem with your system to me. `ios_base::failure` is part of the standard c++ library, and it not finding the symbol hints to a linking problem.
Maybe you have multiple compiler/linker versions or libstdc++ versions installed and are mixing them up somehow? You can use `ldd densecrf.so` to see what exact files are being linked and found at runtime.
I'm afraid there's not much more I can help unless I can reproduce the error myself.

**Comment by JiayunLi** [comment] 2017-02-23 18:48
Thanks! I am able to solve the problem by installing libgcc in the anaconda virtual environment.

**Comment by lucasb-eyer** [comment] 2017-02-23 18:56
Awesome! If you would be so kind to give me the exact command you used to fix this, I could include it in the README and it might help others getting the same error.

**Comment by JiayunLi** [comment] 2017-02-23 19:02
Cool! I Google for similar problem, and found this one  <https://github.com/explosion/sense2vec/issues/19> The solution they mentioned solved my problem. 
To install libgcc, I used `conda install libgcc`

**Comment by lucasb-eyer** [comment] 2017-02-23 19:08
Thank you! I'll close this issue then.

**Closed by lucasb-eyer** 2017-02-23 19:08 UTC
