### ISSUE TITLE
What is the meaning of the parameters:sxy srgb compat

### ISSUE THREAD

**Issue by mshmoon** [lucasb-eyer/pydensecrf#68] opened 2018-06-05 04:09 UTC
I do not understand the meaning of these parameters :sxy srgb compat,

**Comment by lucasb-eyer** [comment] 2018-06-05 06:22
Duplicate of #45. It is described in the README to which symbols in the paper they correspond, and the paper itself describes their meaning in the whole method.

**Closed by lucasb-eyer** 2018-06-05 06:22 UTC
